MERCHANT = [
  {m: "Aerie", v:"aerie"},
  {m: "1-800-Flowers", v:"1800-flowers"},
  {m: "Abercrombie & Fitch", v:"abercrombie-and-fitch"},
  {m: "Academy Sports", v:"academy-sports"},
  {m: "Adidas", v:"adidas"},
  {m: "Air BNB", v:"air-bnb"},
  {m: "American Express", v:"american-express"},
  {m: "Barnes and Noble", v:"barnes-and-noble"},
  {m: "Bass Pro", v:"bass-pro-shops"},
  {m: "Bath & Body Works", v:"bath-and-body-works"},
  {m: "BedandBreakfast.com", v:"bedandbreakfast"},
  {m: "Big Lots", v:"big-lots"},
  {m: "Blaze Pizza", v:"blaze-pizza"},
  {m: "BOJangles'", v:"bo-jangles"},
  {m: "Boscov's", v:"boscovs"},
  {m: "BP Amoco", v:"bp-amoco"},
  {m: "Brookstone", v:"brookstone"},
  {m: "Container Store", v:"container-store"},
  {m: "Crocs", v:"crocs"},
  {m: "CVS Pharmacy", v:"cvs"},
  {m: "Delta", v:"delta"},
  {m: "DSW", v:"dsw"},
  {m: "DXL Destination XL", v:"dxl-destination-xl"},
  {m: "eBay", v:"ebay"},
  {m: "Estee Lauder", v:"estee-lauder"},
  {m: "Fossil", v:"fossil"},
  {m: "Frischs Big Boy", v:"frischs-big-boy"},
  {m: "Fry's Electronics", v:"frys-electronics"},
  {m: "Gander Mountain", v:"gander-mountain"},
  {m: "Golf Galaxy", v:"golf-galaxy"},
  {m: "Gucci", v:"gucci"},
  {m: "Hanna Andersson", v:"hanna-andersson"},
  {m: "Harris teeter", v:"harris-teeter"},
  {m: "Hobby Lobby", v:"hobby-lobby"},
  {m: "Hooters", v:"hooters"},
  {m: "Jared", v:"jared"},
  {m: "Jiffy Lube", v:"jiffy-lube"},
  {m: "Jo Ann Fabrics", v:"jo-ann-fabrics"},
  {m: "Joes Crab Shack", v:"joes-crab-shack"},
  {m: "Journey's", v:"journeys"},
  {m: "KFC", v:"kfc"},
  {m: "Kirkland's", v:"kirklands"},
  {m: "Kohls", v:"kohls"},
  {m: "Landry's Restaurants", v:"landrys-restaurants"},
  {m: "Loft", v:"loft"},
  {m: "Lucy Activwear", v:"lucy-activewear"},
  {m: "Lulu Lemon", v:"lulu-lemon"},
  {m: "Maggiano's Little Italy", v:"maggianos-little-italy"},
  {m: "Mastercard", v:"master-card"},
  {m: "Menard's", v:"menards"},
  {m: "Michaels", v:"michaels"},
  {m: "Mobil Gas", v:"mobil-gas"},
  {m: "Office Depot", v:"office-depot"},
  {m: "Office Max", v:"office-max"},
  {m: "Omaha Steaks", v:"omaha-steaks"},
  {m: "On The Border", v:"on-the-border"},
  {m: "PacSun", v:"pac-sun"},
  {m: "Pei Wei", v:"pei-wei"},
  {m: "Pier 1 imports", v:"pier-1-imports"},
  {m: "Rainforest Cafe", v:"rainforest-cafe"},
  {m: "Rue 21", v:"rue21"},
  {m: "Saks Fifth Avenue", v:"saks-fifth-avenue"},
  {m: "Smoothie King", v:"smoothie-king"},
  {m: "Soma Intimates", v:"soma-intimates"},
  {m: "Sonic", v:"sonic"},
  {m: "Spa Wish", v:"spa-wish"},
  {m: "Staples", v:"staples"},
  {m: "Taco Bell", v:"taco-bell"},
  {m: "TJ Maxx", v:"tj-maxx"},
  {m: "Toys R Us", v:"toys-r-us"},
  {m: "Tropical Smoothie Cafe", v:"tropical-smoothie-cafe"},
  {m: "Victorias Secret", v:"victorias-secret"},
  {m: "Visa Gift Card", v:"visa-gift-card"},
  {m: "Zaxbys", v:"zaxbys"},
  {m: "Aldo", v:"aldo"},
  {m: "AMC Theatres", v:"amc-theatres"},
  {m: "American Apparel", v:"american-apparel"},
  {m: "American Eagle", v:"american-eagle"},
  {m: "Anna's Linens", v:"annas-linens"},
  {m: "Anthropologie", v:"anthropologie"},
  {m: "Applebee's", v:"applebees"},
  {m: "Arby's", v:"arbys"},
  {m: "Armani Exchange", v:"armani-exchange"},
  {m: "Ashley Stewart", v:"ashley-stewart"},
  {m: "At home", v:"at-home"},
  {m: "Autozone", v:"auto-zone"},
  {m: "Avenue", v:"avenue"},
  {m: "Ballard Designs", v:"ballard-designs"},
  {m: "Bass (G.H bass & Company)", v:"bass"},
  {m: "Belk", v:"belk"},
  {m: "Bennigan's", v:"bennigans"},
  {m: "Big 5 Sporting Goods", v:"big-5-sporting-goods"},
  {m: "Blick Art Materials", v:"blick-art-materials"},
  {m: "Bloomingdales", v: "bloomingdales"},
  {m: "Bob Evans", v:"bob-evans-restaurants"},
  {m: "Bonefish Grill", v:"bonefish-grill"},
  {m: "Books A Million", v:"books-a-million"},
  {m: "Boston Market", v:"boston-market"},
  {m: "Bravo! Cucina ltaliano", v:"bravo-cucina-italiano"},
  {m: "Brooks Brothers", v:"brooks-brothers"},
  {m: "Buca Di Beppo", v:"buca-di-beppo"},
  {m: "Buffalo Wild Wings", v:"buffalo-wild-wings"},
  {m: "Build A Bear", v:"build-a-bear"},
  {m: "Burger King", v:"burger-king"},
  {m: "California Pizza Kitchen", v:"california-Pizza-Kitchen"},
  {m: "Carmike Cinemas", v:"carmike-cinemas"},
  {m: "Carrabbas Italian Grill", v:"carrabbas-italian-grill"},
  {m: "Carters", v:"carters"},
  {m: "Catherines", v:"catherines"},
  {m: "Cato", v:"cato"},
  {m: "Charming Charlie", v:"charming-charlie"},
  {m: "Chick-fil-A", v:"chick-fil-a"},
  {m: "Chico‘s", v:"chicos"},
  {m: "Chipotle", v:"chipotle"},
  {m: "Christopher & Banks", v:"christopher-and-banks"},
  {m: "Cinema De Lux", v:"cinema-de-lux"},
  {m: "Claim Jumper Restaurants", v:"claim-jumper-restaurants"},
  {m: "Claires", v:"claires"},
  {m: "Clarks", v:"clarks"},
  {m: "Club Monaco", v:"club-monaco"},
  {m: "Coffee Bean & Tea Leaf", v:"coffee-bean-and-tea-leaf"},
  {m: "Cold Stone Creamery", v: "cold-stone-creamery"},
  {m: "Cole Haan", v: "cole-haan"},
  {m: "Columbia Sportswear", v:"columbia-sportswear"},
  {m: "Cracker Barrel", v:"cracker-barrel"},
  {m: "Crazy 8", v: "crazy-8"},
  {m: "Darden Restaurants", v:"darden-restaurants"},
  {m: "Dave and Busters", v:"dave-and-busters"},
  {m: "Dell", v:"dell"},
  {m: "Denny's", v:"dennys"},
  {m: "Destination Maternity", v:"destination-maternity"},
  {m: "Dillards", v:"dillards"},
  {m: "Dress Barn", v:"dress-barn"},
  {m: "Dunkin Donuts", v:"dunkin-donuts"},
  {m: "Eddie Bauer", v:"eddie-bauer"},
  {m: "Einstein Bros Bagels", v:"einstein-bros-bagels"},
  {m: "Express", v:"express"},
  {m: "Exxon", v:"exxon"},
  {m: "Family Dollar", v:"family-dollar"},
  {m: "Famous Dave's", v:"famous-daves"},
  {m: "Foot Locker", v:"foot-locker"},
  {m: "Forever 21", v:"forever-21"},
  {m: "Francesca's", v:"francescas"},
  {m: "Free People", v:"free-people"},
  {m: "Friendly's", v:"friendlys"},
  {m: "Gamestop", v:"game-stop"},
  {m: "Gilly Hicks Sydney", v:"gilly-hicks-sydney"},
  {m: "GNC", v:"gnc"},
  {m: "Godiva	", v:"godiva"},
  {m: "Golden Corral", v:"golden-corral"},
  {m: "Gordmans	", v:"gordmans"},
  {m: "Gordon Biersch", v:"gordon-biersch"},
  {m: "Guess", v:"guess"},
  {m: "Gymboree", v:"gymboree"},
  {m: "H&M", v:"h-and-m"},
  {m: "Harbor Freight Tools", v:"harbor-freight-tools"},
  {m: "Hibbett Sports	", v:"hibbett-sports"},
  {m: "Hollister", v:"hollister"},
  {m: "Home Depot", v:"home-depot"},
  {m: "Houlihan's", v:"houlihans"},
  {m: "HP", v:"hp"},
  {m: "Hyatt Hotels", v:"hyatt-hotels"},
  {m: "iHop", v:"ihop"},
  {m: "iTunes", v:"i-tunes"},
  {m: "J Crew", v:"j-crew"},
  {m: "JCPenney", v:"jcpenney"},
  {m: "Johnny Rockets	", v:"johnny-rockets"},
  {m: "Joseph A Bank", v:"joseph-a-bank"},
  {m: "Justice", v:"justice"},
  {m: "Krispy Kreme", v:"krispy-kreme"},
  {m: "Kroger", v:"kroger"},  
  {m: "La Salsa Fresh Mexican Grill", v: "la-salsa-fresh-mexican-grill"},
  {m: "Legal Sea Foods", v: "legal-sea-foods"},
  {m: "Lego Store", v: "lego-store"},
  {m: "Limited too", v: "limited-too"},
  {m: "Logan's Roadhouse", v: "logans-roadhouse"},
  {m: "Longhorn Steakhouse", v: "longhorn-steakhouse"},
  {m: "Lord & Taylor", v: "lord-and-taylor"},
  {m: "MAC Cosmetics", v: "mac-cosmetics"},
  {m: "Macy's", v: "macys"},
  {m: "Mandee", v: "mandee"},
  {m: "Marshalls", v: "marshalls"},
  {m: "Maurices", v: "maurices"},
  {m: "McDonalds", v: "mcdonalds"},
  {m: "Melting Pot", v: "melting-pot"},
  {m: "Mens Wearhouse", v: "mens-wearhouse"},
  {m: "Michaels	", v: "michaels"},
  {m: "Moe's Southwest Grill", v: "moes-southwest-grill"},
  {m: "NBA Store", v: "nba-store"},
  {m: "New York & Company", v: "new-york-and-company"},
  {m: "Nordstrom", v: "nordstrom"},
  {m: "North Face", v: "north-face"},
  {m: "OCharleys", v: "ocharleys"},
  {m: "Outback Steakhouse", v: "outback-steakhouse"},
  {m: "P F Changs", v: "p-f-changs"},
  {m: "Panda Express", v: "panda-express"},
  {m: "Panera Bread", v: "panera-bread"},
  {m: "Patagonia", v: "patagonia"},
  {m: "Peebles", v: "peebles"},
  {m: "Pinkberry", v: "pinkberry"},
  {m: "Pottery Barn", v: "pottery-barn"},
  {m: "Puma", v: "puma"},
  {m: "Rack room shoes", v: "rack-room-shoes"},
  {m: "Red Lobster", v: "red-lobster"},
  {m: "Red Robin", v: "red-robin"},
  {m: "Regis Salons", v: "regis-salons"},
  {m: "Restaurants Unlimited", v: "restaurants-unlimited"},
  {m: "Ross", v: "ross"},
  {m: "Ruby Tuesday", v: "ruby-tuesday"},
  {m: "Sally Beauty Supply", v: "sally-beauty-supply"},
  {m: "Shell", v: "shell"},
  {m: "Showcase Cinemas", v: "showcase-cinemas"},
  {m: "Smokey Bones Grill", v: "smokey-bones-grill"},
  {m: "Soma IntimatesSpa Finder", v: "soma-intimatesspa-finder"},
  {m: "Speedway Motors", v: "speedway-motors"},
  {m: "Speedway SuperAmerica", v: "speedway-superamerica"},
  {m: "Steak & Shake", v: "steak-and-shake"},
  {m: "Steve Madden Shoes", v: "steve-madden-shoes"},
  {m: "Subway", v: "subway"},
  {m: "Sunoco", v: "sunoco"},
  {m: "Tahoe Joe's", v: "tahoe-joes"},
  {m: "Talbots", v: "talbots"},
  {m: "Target", v: "target"},
  {m: "Texas Roadhouse", v: "texas-soadhouse"},
  {m: "TGI Friday's", v: "tgi-fridays"},
  {m: "The Limited", v: "the-limited"},
  {m: "Under Armour", v: "under-armour"},
  {m: "Uno Chicago Grill", v: "uno-chicago-grill"},
  {m: "Urban Outfitters", v: "urban-outfitters"},
  {m: "Van Heusen", v: "van-heusen"},
  {m: "Vans", v: "vans"},
  {m: "Vera Bradley", v: "vera-bradley"},
  {m: "Von Maur", v: "von-maur"},
  {m: "Walgreens", v: "walgreens"},
  {m: "Walmart", v: "walmart"},
  {m: "West Elm", v: "west-elm"},
  {m: "Wet Seal", v: "wet-seal"},
  {m: "White Castle", v: "white-castle"},
  {m: "White House Black Market", v: "white-house-black-market"},
  {m: "Whole Foods", v: "whole-foods"},
  {m: "Zumiez", v: "zumiez"},
  {m: "Jockey", v: "jockey"},
  {m: "Lowes", v: "lowes"},
  {m: "Five Guys", v: "five-guys"},
  {m: "Wingstop", v: "wingstop"},
  {m: "Noodles & company", v: "noodles-and-company"},
  {m: "Pandora", v: "pandora-jewelry"},
  {m: "Topshop", v: "topshop"},
  {m: "Movie Stop", v: "moviestop"},
  {m: "Pappas Restaurants", v: "pappas-restaurants"},
  {m: "Pappadeaux Seafood Kitchen", v: "pappadeaux-seafood-kitchen"},
  {m: "Marquee Las Vegas", v: "marquee-las-vegas"},
  {m: "Tommy Hilfiger", v: "tommy-hilfiger"},
  {m: "Erehwon Mountain Outfitter", v: "erehwon-mountain-outfitter"},
  {m: "Party City", v: "party-city"},
  {m: "Quick Trip", v: "quick-trip"},
  {m: "Seasons 52", v: "seasons-52"},
  {m: "Five below", v: "five-below"},
  {m: "Google Play", v: "google-play"},
  {m: "Hugo Boss", v: "hugo-boss"},
  {m: "Hanes", v: "hanes"},
  {m: "Pet Value", v: "pet-value"},
  {m: "Perry Ellis", v: "perry-ellis"},
  {m: "Mango", v: "mango"},
  {m: "Mastro Steakhouse", v: "mastro-steakhouse"},
  {m: "Jimmy Johns", v: "jimmy-johns"},
  {m: "MovieTavern", v: "movie-tavern"},
  {m: "Peapod", v: "peapod"},
  {m: "Diesel", v: "diesel"},
  {m: "Earth Fare", v: "earth-fare"},
  {m: "Pet Supermarket", v: "pet-supermarket"},
  {m: "Firehouse  Subs", v: "firehouse-subs"},
  {m: "Vineyard Vines", v: "vineyard-vines"},
  {m: "Pollo Tropical", v: "pollo-tropical"},
  {m: "Smashburger", v: "smashburger"},
  {m: "Plato's Closet", v: "platos-closet"},
  {m: "Mitchell's Fish Market", v: "mitchells-fish-market"},
  {m: "Oakley", v: "oakley"},
  {m: "Haggar", v: "haggar"},
  {m: "Which Wich", v: "which-wich"},
  {m: "Potbelly", v: "potbelly"}
]